# Note: Parameters can be put into common/function_config_<environment>.yaml
# if you do not need to vary them between your functions!
schedules_client_id: d9b2bd26-2d84-4960-bbdc-ecdd9743975d
schedules_tenant_id: 0d75f6b8-c6b9-4e84-baca-503e08aa7e4a
