name: Code Quality checks for PRs

on:
  pull_request:

jobs:
  pre-commit:
    name: Pre-Commit checks
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - uses: pre-commit/action@v3.0.1
